name: apk-builder
run-name: ${{ github.actor }} inicialized flet build apk 
on: [push]

jobs:
    flet-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
                
            - run: | 
                python -m pip install --upgrade pip
                pip install flet[all]
            
            - run: flet build apk . --module-name "permission_handler.py"

            - name: APK Upload
              uses: actions/upload-artifact@v4
              with:
                  name: your-apk
                  path: build/apk/*.apk
                  retention-days: 1
